apiVersion: v1
kind: Service
metadata:
    name: musicimage
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
        app: musicimage
